[build]
  command = "npm run build"
  publish = "public"  # Adjust if your build output directory is different

[[headers]]
  for = "/.*bundle.js$"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/(.+)\\.([a-zA-Z]{2,4})$"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200