services:
  - type: web
    name: devmentor-frontend
    env: static
    buildCommand: |
      npm install -g pnpm
      pnpm install --no-frozen-lockfile
      pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-store
          - key: Access-Control-Allow-Origin
            value: "*"
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.9