
// Day of the week options
export const daysOfTheWeek = [
    { value: 'monday', label: 'Monday' },
    { value: 'tuesday', label: 'Tuesday' },
    { value: 'wednesday', label: 'Wednesday' },
    { value: 'thursday', label: 'Thursday' },
    { value: 'friday', label: 'Friday' },
    { value: 'saturday', label: 'Saturday' },
    { value: 'sunday', label: 'Sunday' },
];


// Option length
export const optionLength = [
    { value: 1, label: 'general' },
    {
        value: 2,
        label:
            'Evil is the moment when I lack the strength to be true to the Good that compels me.',
    },
    {
        value: 3,
        label:
            "It is now an easy matter to spell out the ethic of a truth: 'Do all that you can to persevere in that which exceeds your perseverance. Persevere in the interruption. Seize in your being that which has seized and broken you.",
    },
];

// Grouped options
export const groupedOptions = [
    {
        label: 'Skills',
        options: skillsList,
    },
    {
        label: 'State',
        options: stateOptions,
    },
];

// Skills options
export const skillsList = [
    { id: 1, label: 'Python' },
    { id: 2, label: 'JavaScript' },
    { id: 3, label: 'Java' },
    { id: 4, label: 'C++' },
    { id: 5, label: 'C#' },
    { id: 6, label: 'Ruby' },
    { id: 7, label: 'Go' },
    { id: 8, label: 'TypeScript' },
    { id: 9, label: 'PHP' },
    { id: 10, label: 'Swift' },
    { id: 11, label: 'Kotlin' },
    { id: 12, label: 'HTML' },
    { id: 13, label: 'CSS' },
    { id: 14, label: 'React' },
    { id: 15, label: 'Angular' },
    { id: 16, label: 'Vue.js' },
    { id: 17, label: 'Node.js' },
    { id: 18, label: 'Django' },
    { id: 19, label: 'Flask' },
    { id: 20, label: 'ASP.NET' },
    { id: 21, label: 'SQL' },
    { id: 22, label: 'NoSQL' },
    { id: 23, label: 'MySQL' },
    { id: 24, label: 'PostgreSQL' },
    { id: 25, label: 'MongoDB' },
    { id: 26, label: 'Redis' },
    { id: 27, label: 'SQLite' },
    { id: 28, label: 'Oracle DB' },
    { id: 29, label: 'Docker' },
    { id: 30, label: 'Kubernetes' },
    { id: 31, label: 'Jenkins' },
    { id: 32, label: 'Git' },
    { id: 33, label: 'AWS' },
    { id: 34, label: 'Azure' },
    { id: 35, label: 'Google Cloud Platform (GCP)' },
    { id: 36, label: 'Terraform' },
    { id: 37, label: 'Ansible' },
    { id: 38, label: 'iOS Development' },
    { id: 39, label: 'Android Development' },
    { id: 40, label: 'React Native' },
    { id: 41, label: 'Flutter' },
    { id: 42, label: 'Agile' },
    { id: 43, label: 'Scrum' },
    { id: 44, label: 'Test-Driven Development (TDD)' },
    { id: 45, label: 'Continuous Integration/Continuous Deployment (CI/CD)' },
    { id: 46, label: 'Network Security' },
    { id: 47, label: 'Application Security' },
    { id: 48, label: 'Ethical Hacking' },
    { id: 49, label: 'Cryptography' },
    { id: 50, label: 'Pandas' },
    { id: 51, label: 'NumPy' },
    { id: 52, label: 'Scikit-learn' },
    { id: 53, label: 'TensorFlow' },
    { id: 54, label: 'PyTorch' },
    { id: 55, label: 'Data Visualization' },
    { id: 56, label: 'Data Analysis' },
    { id: 57, label: 'API Development' },
    { id: 58, label: 'Microservices' },
    { id: 59, label: 'RESTful Services' },
    { id: 60, label: 'GraphQL' },
    { id: 61, label: 'Software Architecture' },
    { id: 62, label: 'Design Patterns' },
    { id: 63, label: 'Performance Optimization' },
    { id: 64, label: 'Code Review' }
];

// State options
export const stateOptions = [
    { value: 'AL', label: 'AL - Alabama' },
    { value: 'AK', label: 'AK - Alaska' },
    { value: 'AZ', label: 'AZ - Arizona' },
    { value: 'AR', label: 'AR - Arkansas' },
    { value: 'CA', label: 'CA - California' },
    { value: 'CO', label: 'CO - Colorado' },
    { value: 'CT', label: 'CT - Connecticut' },
    { value: 'DE', label: 'DE - Delaware' },
    { value: 'FL', label: 'FL - Florida' },
    { value: 'GA', label: 'GA - Georgia' },
    { value: 'HI', label: 'HI - Hawaii' },
    { value: 'ID', label: 'ID - Idaho' },
    { value: 'IL', label: 'IL - Illinois' },
    { value: 'IN', label: 'IN - Indiana' },
    { value: 'IA', label: 'IA - Iowa' },
    { value: 'KS', label: 'KS - Kansas' },
    { value: 'KY', label: 'KY - Kentucky' },
    { value: 'LA', label: 'LA - Louisiana' },
    { value: 'ME', label: 'ME - Maine' },
    { value: 'MD', label: 'MD - Maryland' },
    { value: 'MA', label: 'MA - Massachusetts' },
    { value: 'MI', label: 'MI - Michigan' },
    { value: 'MN', label: 'MN - Minnesota' },
    { value: 'MS', label: 'MS - Mississippi' },
    { value: 'MO', label: 'MO - Missouri' },
    { value: 'MT', label: 'MT - Montana' },
    { value: 'NE', label: 'NE - Nebraska' },
    { value: 'NV', label: 'NV - Nevada' },
    { value: 'NH', label: 'NH - New Hampshire' },
    { value: 'NJ', label: 'NJ - New Jersey' },
    { value: 'NM', label: 'NM - New Mexico' },
    { value: 'NY', label: 'NY - New York' },
    { value: 'NC', label: 'NC - North Carolina' },
    { value: 'ND', label: 'ND - North Dakota' },
    { value: 'OH', label: 'OH - Ohio' },
    { value: 'OK', label: 'OK - Oklahoma' },
    { value: 'OR', label: 'OR - Oregon' },
    { value: 'PA', label: 'PA - Pennsylvania' },
    { value: 'RI', label: 'RI - Rhode Island' },
    { value: 'SC', label: 'SC - South Carolina' },
    { value: 'SD', label: 'SD - South Dakota' },
    { value: 'TN', label: 'TN - Tennessee' },
    { value: 'TX', label: 'TX - Texas' },
    { value: 'UT', label: 'UT - Utah' },
    { value: 'VT', label: 'VT - Vermont' },
    { value: 'VA', label: 'VA - Virginia' },
    { value: 'WA', label: 'WA - Washington' },
    { value: 'WV', label: 'WV - West Virginia' },
    { value: 'WI', label: 'WI - Wisconsin' },
    { value: 'WY', label: 'WY - Wyoming' }
];

// Country options
export const countryOptions = [
    { id: 196, label: 'United States of America (USA)' },
    { id: 1, label: 'Afghanistan' },
    { id: 2, label: 'Albania' },
    { id: 3, label: 'Algeria' },
    { id: 4, label: 'American Samoa' },
    { id: 5, label: 'Andorra' },
    { id: 6, label: 'Angola' },
    { id: 7, label: 'Anguilla' },
    { id: 8, label: 'Antarctica' },
    { id: 9, label: 'Antigua and Barbuda' },
    { id: 10, label: 'Argentina' },
    { id: 11, label: 'Armenia' },
    { id: 12, label: 'Aruba' },
    { id: 13, label: 'Australia' },
    { id: 14, label: 'Austria' },
    { id: 15, label: 'Azerbaijan' },
    { id: 16, label: 'Bahamas' },
    { id: 17, label: 'Bahrain' },
    { id: 18, label: 'Bangladesh' },
    { id: 19, label: 'Barbados' },
    { id: 20, label: 'Belarus' },
    { id: 21, label: 'Belgium' },
    { id: 22, label: 'Belize' },
    { id: 23, label: 'Benin' },
    { id: 24, label: 'Bermuda' },
    { id: 25, label: 'Bhutan' },
    { id: 26, label: 'Bolivia' },
    { id: 27, label: 'Bosnia and Herzegovina' },
    { id: 28, label: 'Botswana' },
    { id: 29, label: 'Brazil' },
    { id: 30, label: 'British Indian Ocean Territory' },
    { id: 31, label: 'Brunei Darussalam' },
    { id: 32, label: 'Bulgaria' },
    { id: 33, label: 'Burkina Faso' },
    { id: 34, label: 'Burundi' },
    { id: 35, label: 'Cabo Verde' },
    { id: 36, label: 'Cambodia' },
    { id: 37, label: 'Cameroon' },
    { id: 38, label: 'Canada' },
    { id: 39, label: 'Cayman Islands' },
    { id: 40, label: 'Central African Republic' },
    { id: 41, label: 'Chad' },
    { id: 42, label: 'Chile' },
    { id: 43, label: 'China' },
    { id: 44, label: 'Colombia' },
    { id: 45, label: 'Comoros' },
    { id: 46, label: 'Congo' },
    { id: 47, label: 'Congo, Democratic Republic of the' },
    { id: 48, label: 'Cook Islands' },
    { id: 49, label: 'Costa Rica' },
    { id: 50, label: 'Côte d\'Ivoire' },
    { id: 51, label: 'Croatia' },
    { id: 52, label: 'Cuba' },
    { id: 53, label: 'Cyprus' },
    { id: 54, label: 'Czech Republic' },
    { id: 55, label: 'Denmark' },
    { id: 56, label: 'Djibouti' },
    { id: 57, label: 'Dominica' },
    { id: 58, label: 'Dominican Republic' },
    { id: 59, label: 'Ecuador' },
    { id: 60, label: 'Egypt' },
    { id: 61, label: 'El Salvador' },
    { id: 62, label: 'Equatorial Guinea' },
    { id: 63, label: 'Eritrea' },
    { id: 64, label: 'Estonia' },
    { id: 65, label: 'Eswatini' },
    { id: 66, label: 'Ethiopia' },
    { id: 67, label: 'Fiji' },
    { id: 68, label: 'Finland' },
    { id: 69, label: 'France' },
    { id: 70, label: 'Gabon' },
    { id: 71, label: 'Gambia' },
    { id: 72, label: 'Georgia' },
    { id: 73, label: 'Germany' },
    { id: 74, label: 'Ghana' },
    { id: 75, label: 'Greece' },
    { id: 76, label: 'Grenada' },
    { id: 77, label: 'Guam' },
    { id: 78, label: 'Guatemala' },
    { id: 79, label: 'Guinea' },
    { id: 80, label: 'Guinea-Bissau' },
    { id: 81, label: 'Guyana' },
    { id: 82, label: 'Haiti' },
    { id: 83, label: 'Honduras' },
    { id: 84, label: 'Hungary' },
    { id: 85, label: 'Iceland' },
    { id: 86, label: 'India' },
    { id: 87, label: 'Indonesia' },
    { id: 88, label: 'Iran, Islamic Republic of' },
    { id: 89, label: 'Iraq' },
    { id: 90, label: 'Ireland' },
    { id: 91, label: 'Israel' },
    { id: 92, label: 'Italy' },
    { id: 93, label: 'Jamaica' },
    { id: 94, label: 'Japan' },
    { id: 95, label: 'Jordan' },
    { id: 96, label: 'Kazakhstan' },
    { id: 97, label: 'Kenya' },
    { id: 98, label: 'Kiribati' },
    { id: 99, label: 'Korea, Democratic People\'s Republic of' },
    { id: 100, label: 'Korea, Republic of' },
    { id: 101, label: 'Kuwait' },
    { id: 102, label: 'Kyrgyzstan' },
    { id: 103, label: 'Lao People\'s Democratic Republic' },
    { id: 104, label: 'Latvia' },
    { id: 105, label: 'Lebanon' },
    { id: 106, label: 'Lesotho' },
    { id: 107, label: 'Liberia' },
    { id: 108, label: 'Libya' },
    { id: 109, label: 'Liechtenstein' },
    { id: 110, label: 'Lithuania' },
    { id: 111, label: 'Luxembourg' },
    { id: 112, label: 'Madagascar' },
    { id: 113, label: 'Malawi' },
    { id: 114, label: 'Malaysia' },
    { id: 115, label: 'Maldives' },
    { id: 116, label: 'Mali' },
    { id: 117, label: 'Malta' },
    { id: 118, label: 'Marshall Islands' },
    { id: 119, label: 'Mauritania' },
    { id: 120, label: 'Mauritius' },
    { id: 121, label: 'Mexico' },
    { id: 122, label: 'Micronesia, Federated States of' },
    { id: 123, label: 'Moldova, Republic of' },
    { id: 124, label: 'Monaco' },
    { id: 125, label: 'Mongolia' },
    { id: 126, label: 'Montenegro' },
    { id: 127, label: 'Morocco' },
    { id: 128, label: 'Mozambique' },
    { id: 129, label: 'Myanmar' },
    { id: 130, label: 'Namibia' },
    { id: 131, label: 'Nauru' },
    { id: 132, label: 'Nepal' },
    { id: 133, label: 'Netherlands' },
    { id: 134, label: 'New Zealand' },
    { id: 135, label: 'Nicaragua' },
    { id: 136, label: 'Niger' },
    { id: 137, label: 'Nigeria' },
    { id: 138, label: 'North Macedonia' },
    { id: 139, label: 'Norway' },
    { id: 140, label: 'Oman' },
    { id: 141, label: 'Pakistan' },
    { id: 142, label: 'Palau' },
    { id: 143, label: 'Palestine, State of' },
    { id: 144, label: 'Panama' },
    { id: 145, label: 'Papua New Guinea' },
    { id: 146, label: 'Paraguay' },
    { id: 147, label: 'Peru' },
    { id: 148, label: 'Philippines' },
    { id: 149, label: 'Poland' },
    { id: 150, label: 'Portugal' },
    { id: 151, label: 'Qatar' },
    { id: 152, label: 'Romania' },
    { id: 153, label: 'Russian Federation' },
    { id: 154, label: 'Rwanda' },
    { id: 155, label: 'Saint Kitts and Nevis' },
    { id: 156, label: 'Saint Lucia' },
    { id: 157, label: 'Saint Vincent and the Grenadines' },
    { id: 158, label: 'Samoa' },
    { id: 159, label: 'San Marino' },
    { id: 160, label: 'Sao Tome and Principe' },
    { id: 161, label: 'Saudi Arabia' },
    { id: 162, label: 'Senegal' },
    { id: 163, label: 'Serbia' },
    { id: 164, label: 'Seychelles' },
    { id: 165, label: 'Sierra Leone' },
    { id: 166, label: 'Singapore' },
    { id: 167, label: 'Slovakia' },
    { id: 168, label: 'Slovenia' },
    { id: 169, label: 'Solomon Islands' },
    { id: 170, label: 'Somalia' },
    { id: 171, label: 'South Africa' },
    { id: 172, label: 'South Sudan' },
    { id: 173, label: 'Spain' },
    { id: 174, label: 'Sri Lanka' },
    { id: 175, label: 'Sudan' },
    { id: 176, label: 'Suriname' },
    { id: 177, label: 'Sweden' },
    { id: 178, label: 'Switzerland' },
    { id: 179, label: 'Syrian Arab Republic' },
    { id: 180, label: 'Taiwan, Province of China' },
    { id: 181, label: 'Tajikistan' },
    { id: 182, label: 'Tanzania, United Republic of' },
    { id: 183, label: 'Thailand' },
    { id: 184, label: 'Timor-Leste' },
    { id: 185, label: 'Togo' },
    { id: 186, label: 'Tonga' },
    { id: 187, label: 'Trinidad and Tobago' },
    { id: 188, label: 'Tunisia' },
    { id: 189, label: 'Turkey' },
    { id: 190, label: 'Turkmenistan' },
    { id: 191, label: 'Tuvalu' },
    { id: 192, label: 'Uganda' },
    { id: 193, label: 'Ukraine' },
    { id: 194, label: 'United Arab Emirates' },
    { id: 195, label: 'United Kingdom of Great Britain and Northern Ireland' },
    
    { id: 197, label: 'Uruguay' },
    { id: 198, label: 'Uzbekistan' },
    { id: 199, label: 'Vanuatu' },
    { id: 200, label: 'Venezuela, Bolivarian Republic of' },
    { id: 201, label: 'Viet Nam' },
    { id: 202, label: 'Yemen' },
    { id: 203, label: 'Zambia' },
    { id: 204, label: 'Zimbabwe' }
];