
// Day of the week options
export const daysOfTheWeek = [
    { value: 'monday', label: 'Monday' },
    { value: 'tuesday', label: 'Tuesday' },
    { value: 'wednesday', label: 'Wednesday' },
    { value: 'thursday', label: 'Thursday' },
    { value: 'friday', label: 'Friday' },
    { value: 'saturday', label: 'Saturday' },
    { value: 'sunday', label: 'Sunday' },
];

// State options
export const stateOptions = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AS', label: 'American Samoa' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'DC', label: 'District Of Columbia' },
    { value: 'FM', label: 'Federated States Of Micronesia' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'GU', label: 'Guam' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MH', label: 'Marshall Islands' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'MP', label: 'Northern Mariana Islands' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PW', label: 'Palau' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'PR', label: 'Puerto Rico' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VI', label: 'Virgin Islands' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' },
];

// Option length
export const optionLength = [
    { value: 1, label: 'general' },
    {
        value: 2,
        label:
            'Evil is the moment when I lack the strength to be true to the Good that compels me.',
    },
    {
        value: 3,
        label:
            "It is now an easy matter to spell out the ethic of a truth: 'Do all that you can to persevere in that which exceeds your perseverance. Persevere in the interruption. Seize in your being that which has seized and broken you.",
    },
];

// Dog options
export const dogOptions = [
    { id: 1, label: 'Chihuahua' },
    { id: 2, label: 'Bulldog' },
    { id: 3, label: 'Dachshund' },
    { id: 4, label: 'Akita' },
];

// Grouped options
export const groupedOptions = [
    {
        label: 'Skills',
        options: skillsList,
    },
    {
        label: 'State',
        options: stateOptions,
    },
];

// Skills options
export const skillsList = [
    { id: 1, label: 'Python' },
    { id: 2, label: 'JavaScript' },
    { id: 3, label: 'Java' },
    { id: 4, label: 'C++' },
    { id: 5, label: 'C#' },
    { id: 6, label: 'Ruby' },
    { id: 7, label: 'Go' },
    { id: 8, label: 'TypeScript' },
    { id: 9, label: 'PHP' },
    { id: 10, label: 'Swift' },
    { id: 11, label: 'Kotlin' },
    { id: 12, label: 'HTML' },
    { id: 13, label: 'CSS' },
    { id: 14, label: 'React' },
    { id: 15, label: 'Angular' },
    { id: 16, label: 'Vue.js' },
    { id: 17, label: 'Node.js' },
    { id: 18, label: 'Django' },
    { id: 19, label: 'Flask' },
    { id: 20, label: 'ASP.NET' },
    { id: 21, label: 'SQL' },
    { id: 22, label: 'NoSQL' },
    { id: 23, label: 'MySQL' },
    { id: 24, label: 'PostgreSQL' },
    { id: 25, label: 'MongoDB' },
    { id: 26, label: 'Redis' },
    { id: 27, label: 'SQLite' },
    { id: 28, label: 'Oracle DB' },
    { id: 29, label: 'Docker' },
    { id: 30, label: 'Kubernetes' },
    { id: 31, label: 'Jenkins' },
    { id: 32, label: 'Git' },
    { id: 33, label: 'AWS' },
    { id: 34, label: 'Azure' },
    { id: 35, label: 'Google Cloud Platform (GCP)' },
    { id: 36, label: 'Terraform' },
    { id: 37, label: 'Ansible' },
    { id: 38, label: 'iOS Development' },
    { id: 39, label: 'Android Development' },
    { id: 40, label: 'React Native' },
    { id: 41, label: 'Flutter' },
    { id: 42, label: 'Agile' },
    { id: 43, label: 'Scrum' },
    { id: 44, label: 'Test-Driven Development (TDD)' },
    { id: 45, label: 'Continuous Integration/Continuous Deployment (CI/CD)' },
    { id: 46, label: 'Network Security' },
    { id: 47, label: 'Application Security' },
    { id: 48, label: 'Ethical Hacking' },
    { id: 49, label: 'Cryptography' },
    { id: 50, label: 'Pandas' },
    { id: 51, label: 'NumPy' },
    { id: 52, label: 'Scikit-learn' },
    { id: 53, label: 'TensorFlow' },
    { id: 54, label: 'PyTorch' },
    { id: 55, label: 'Data Visualization' },
    { id: 56, label: 'Data Analysis' },
    { id: 57, label: 'API Development' },
    { id: 58, label: 'Microservices' },
    { id: 59, label: 'RESTful Services' },
    { id: 60, label: 'GraphQL' },
    { id: 61, label: 'Software Architecture' },
    { id: 62, label: 'Design Patterns' },
    { id: 63, label: 'Performance Optimization' },
    { id: 64, label: 'Code Review' }
];