"""empty message

Revision ID: 7daaa39a91cb
Revises: 
Create Date: 2024-11-17 05:48:25.937729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daaa39a91cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.Column('about_me', sa.String(length=2500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('nick_name', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('what_state', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('about_me', sa.String(length=2500), nullable=True),
    sa.Column('years_exp', sa.String(length=30), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('days', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_email'), 'mentor', ['email'], unique=True)
    op.create_index(op.f('ix_mentor_phone'), 'mentor', ['phone'], unique=False)
    op.create_table('customer_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('mentor_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('mentor_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('portfolio_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('focus_areas', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('resourceLink', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=25), nullable=False),
    sa.Column('totalHours', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('appointments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('sender', sa.Enum('CUSTOMER', 'MENTOR', name='myenum'), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('session')
    op.drop_table('portfolio_photo')
    op.drop_table('mentor_image')
    op.drop_table('customer_image')
    op.drop_index(op.f('ix_mentor_phone'), table_name='mentor')
    op.drop_index(op.f('ix_mentor_email'), table_name='mentor')
    op.drop_table('mentor')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###